export const FETCH_PAYMENTS_START = 'FETCH_PAYMENTS_START'
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS'
export const ADD_PAYMENT = 'ADD_PAYMENT'
export const DELETE_PAYMENT = "DELETE_PAYMENT"
export const FIRST_START = "FIRST_START"
export const EDIT_PAYMENT = "EDIT_PAYMENT"